[project]
name = "readme_renderer"
description = '''readme_renderer is a library for rendering "readme" ' "descriptions for Warehouse'''
authors = [
  {email = "admin@mail.pypi.org"},
]
license = {file = "LICENSE"}
dynamic = ["version", "classifiers"]

[tool.setuptools.dynamic]
version = {attr = "readme_renderer.__about__.__version__"}
classifiers = {file = "classifiers.txt"}

[project.urls]
urls = "https://github.com/pypa/readme_renderer"

[build-system]
requires = ["setuptools>=40.8.0"]
build-backend = "setuptools.build_meta"

# TODO: Remove when https://github.com/mgedmin/check-manifest/pull/155 released
[tool.check-manifest]
ignore = [".gitpod.yml"]

[tool.coverage.run]
branch = true

[tool.mypy]
strict = true
warn_unused_configs = true
show_error_codes = true
enable_error_code = [
    "ignore-without-code"
]

[[tool.mypy.overrides]]
# These modules do not yet have types available.
module = [
    "cmarkgfm.*"
]
ignore_missing_imports = true
